### ISSUE TITLE
TODO Today (absolutely)

### ISSUE THREAD

**Issue by pierredarrieutort** [pierredarrieutort/Jape#156]
- [x] Add videos (optimized as possible).
~~Check if videos are ables to w150, w500...~~
- [x]  Add own identity on website.
- [x]  Check Vercel issues.
~~Optimize pre-build.~~
